---
- name : This playbook will run windows update
  hosts: tag_Workshop_type_windows
  vars:
    patches:
      - windows10.0-kb4562562-x64_85f4082ff8a2f8bd870495fe864b00306322d0ea.msu 
  tasks:
  - name: Update but Exlude updates based on the update title - basically WinUpdate to current
    win_updates:
      category_name:
      - SecurityUpdates
      - CriticalUpdates
      - Definition Updates
      - Microsoft Defender Antivirus

  - name: Copy accross HotFixes {{ patches }} bundle
    win_copy:
      src: "/var/tmp/{{ item }}"
      dest: C:\
    with_items: "{{ patches }}"

  - name: Install HotFixes bundle
    win_hotfix:
      source: C:\{{ item }}
      state: present
    with_items: "{{ patches }}"
    register: hotfix_install

#  - win_reboot:
#    when: hotfix_install.reboot_required
