---
- name: Deploy a new windows instance 
  hosts: localhost
  #connection: local
  #become: false
  gather_facts: true 
  #tasks:
  #  - name: run pre-check role to make sure workshop will complete provisioning
  #    include_role:
  #      name: workshop_check_setup

  #  - name: run AWS check setup if using AWS
  #    include_role:
  #      name: aws_check_setup
  vars:
    admin_password: ansible123
    ansible_windows_password: Ansible+Red*Hat19!20
    attendance: false
    doubleup: false
    ec2_region: ap-southeast-2
    instance_loc: ec2
    student_total: 1
    towerinstall: false
    workshop_type: windows
  roles: 
    - workshop_check_setup
    - aws_check_setup
    - manage_ec2_instances
    #- windows_ws_setup

- name: Add Ansible User
  hosts: tag_Workshop_type_windows:windows
  gather_facts: true
  vars:
    ansible_windows_password: Ansible+Red*Hat19!20
  tasks:
    - name: Set the password poloicy
      win_security_policy:
        section: System Access
        key: PasswordComplexity
        value: 0

    - name: Replace password
      win_user:
        name: ansible
        password: "{{ ansible_windows_password }}"
        state: present
        groups:
          - Administrators
      async: 0
      poll: 0

