---
- name: Destroy windows instances in AWS
  hosts: localhost
  connection: local
  become: false
  gather_facts: false

  vars:
    ec2_wait: false
    teardown: true
    s3_state: absent
    state: absent
    debug_teardown: false

    admin_password: ansible123
    ansible_windows_password: Ansible+Red*Hat19!20
    ec2_region: ap-southeast-2
    instance_loc: ec2
    student_total: 1
    towerinstall: false
    workshop_type: windows





  tasks:
    - {include_role: {name: manage_ec2_instances}}
    - {include_role: {name: aws_workshop_login_page}, when: create_login_page is defined and create_login_page}
    - {include_role: {name: aws_dns}, when: create_login_page is defined and create_login_page}
    - {include_role: {name: code_server}, when: code_server}
    - {include_role: {name: gitlab-server}, when: workshop_type == "windows"}


    - name: Remove workshop local files
      file:
        dest: "{{ playbook_dir }}/{{ ec2_name_prefix }}"
        state: absent
