---
- name: Multi purpose EC2 playbook - use the create or delete tag
  hosts: localhost
  gather_facts: False
  vars:
    vm_count: 1
    security_group: 'sg-036c04403f8194aba'
    subnet_id: 'subnet-c3295a8a'
    ssh_key_name: 'etg-richard'
    instance_size: 't2.micro'
    instance_tag: 'cattle'
    ami_name: 'ami-1987757b'    # This is the RHEL AMI

  tasks:
  # https://aws.amazon.com/ec2/instance-types/
  # https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/instance-types.html
  - name: Create RHEL instance in ec2
    ec2:
      image: "{{ ami_name }}"
      instance_type: "{{ instance_size }}"
      aws_access_key: "{{ my_aws_access_key }}"
      aws_secret_key: "{{ my_aws_secret_key }}"
      key_name: "{{ ssh_key_name }}"
      region: 'ap-southeast-2'
      wait: yes 
      count: "{{ vm_count|int }}"
      instance_tags:
        Ansible: "{{ instance_tag }}"
      vpc_subnet_id: "{{ subnet_id }}"
      assign_public_ip: yes
      group_id: "{{ security_group }}"  # or you can say 'default' here
    register: ec2
    tags: create

  - name: Wait for SSH to come up
    wait_for:
      host: "{{ item.public_dns_name }}"
      port: 22
      delay: 60
      timeout: 320
      state: started
    with_items: "{{ ec2.instances }}"
    tags: create

  - name: Enumerate all tagged instances in ec2
    ec2_instance_facts:
      region: 'ap-southeast-2'
      filters:
        "tag:Ansible": "{{ instance_tag }}" 
    register: vmfacts 
    tags: 
      - delete
      - create

  - debug: msg="{{ item.instance_id }}"
    with_items: '{{ vmfacts.instances }}'
    tags: 
      - delete 
      - create

  - name: Delete ami instance in ec2
    ec2:
      aws_access_key: "{{ my_aws_access_key }}"
      aws_secret_key: "{{ my_aws_secret_key }}"
      region: 'ap-southeast-2'
      state: absent
      instance_ids: '{{ item.instance_id }}'
    with_items: '{{ vmfacts.instances }}'
    tags: delete 
