---
- hosts: i-0bcd9a5e847e14839
  become: yes
  gather_facts: yes
  vars:
    rhsm_hostname: subscription.rhsm.redhat.com
    rhsm_prefix: '/subscription'
    rhsm_baseurl: 'https://cdn.redhat.com'
    mylablogin: 'gecos'
    rhnlogin: 'rhn-sa-rhailsto'
  tasks:

#  - name: Include vault variables
#    no_log: true
#    include_vars: vault.yml

#  - name: Check on whether there are enabled repos
#    command: '/sbin/subscription-manager repos --list'
#    register: thereberepos 

#  - debug: var=thereberepos

#  - name: disable all inherited repos
#    command: /sbin/subscription-manager repos --disable="*" 
#    when: thereberepos.stdout.find('This system has no repositories') == -1

  - name: set the correct timezone
    file:
      src: /usr/share/zoneinfo/Australia/Sydney
      dest: /etc/timezone
      state: link

  - name: Check if we are on an EC2 instance..?
    uri:
      url: http://169.254.169.254/latest/meta-data/public-ipv4/
      return_content: yes
    register: webpage

  - debug: var=webpage.msg
  - debug: var=inventory_hostname

  - name: disable RHUI update infrastructure
    lineinfile:
      path: /etc/yum/pluginconf.d/rhui-lb.conf
      regexp: '^enabled=1'
      line: 'enabled=0'

  - name: Remove RHN systemid file 
    file:
      name: /etc/sysconfig/rhn/systemid 
      state: absent 
    when: "'OK' in webpage.msg"

  - name: Find repository files
    find:
      paths: /etc/yum.repos.d/
      patterns: '*.repo'
    register: repos
    when: "'OK' in webpage.msg"

  - name: Remove all YUM repositories
    file:
      name: "{{ item.path }}"
      state: absent
    with_items: "{{ repos.files }}"
    when: "'OK' in webpage.msg"

#  - name: Check if system is subscribed
#    command: /sbin/subscription-manager status
#    ignore_errors: yes
#    register: amisubscribed

#  - debug: var=amisubscribed

#  - name: Unregister via subscription-manager
#    command: /sbin/subscription-manager unregister
#    when: amisubscribed.rc == 0

#  - name: System is not registered, executing subscription-manager clean
#    command: /sbin/subscription-manager clean
#    when: amisubscribed.rc != 0

  - name: put the rhsm configuration file in place
    template:
      src: templates/rhsm.conf.j2
      dest: /etc/rhsm/rhsm.conf
      owner: root
      group: root
      mode: 0644

  - name: Subscribe the system to a specific pool by ID.
    redhat_subscription:
      state: present
      username: "{{ rhnlogin }}"
      password: "{{ vault_subscription_manager_password }}"
      auto_attach: true
      #pool: '8a85f9875bc85ec4015bc95ca3aa61f4'
      #pool: '8a85f98b635f3e6d0163cd94eebc65b4'
      force_register: yes

  - name: Enable specific RHEL 7 subscription repos
    command: /sbin/subscription-manager repos --enable={{ item }}
    with_items:
      - 'rhel-7-server-rpms'
      - 'rhel-7-server-extras-rpms'
      - 'rhel-7-server-rhn-tools-rpms'
      - 'rhel-7-server-optional-rpms'

#  - name: Remove the katello agent packages [ https://access.redhat.com/solutions/3162062 ]
#    yum:
#      name: katello-host-tools
#      state: absent

  - name: Install yum-cron
    yum:
      name: yum-cron
      state: latest

  - name: Enable yum-cron
    service:
      name: yum-cron.service
      state: started


#  - name: Ensure the rh cloud repo's file is not present - Azure only
#    file:
#      state: absent
#      path: "/etc/yum.repos.d/rh-cloud.repo"
