---
## This playbook deploys the whole application stack in this site.  

# Apply common configuration to all hosts
- hosts: all
  become: true
  
  roles:
  - geerlingguy.repo-epel
  - common

#  tasks:
#  - name: stop iptables - it's more unhelpful than helpful right now.
#    service: name=firewalld state=stopped
#    when: cloud_provider == "azure"

#  - name: disable iptables on boot.
#    service: name=firewalld enabled=no
#    when: cloud_provider == "azure"

# Configure and deploy database servers.
- hosts: tag_ansible_group_dbservers, dbservers
  become: true

  roles:
  - geerlingguy.mysql 

  tags:
  - db

# Configure and deploy the web servers. Note that we include two roles here,
# the 'base-apache' role which simply sets up Apache, and 'web' which includes
# our example web application.
- hosts: tag_ansible_group_webservers, webserver*
  become: true

  roles:
  - base-apache
  - web
  
  tags:
  - web

# Configure and deploy the load balancer(s).
- hosts: tag_ansible_group_lbservers, lbservers
  become: true

  roles:
  - haproxy
  
  tags:
  - lb

# Configure and deploy the Nagios monitoring node(s).
- hosts: tag_ansible_group_monitoring, monitoring
  become: true

  roles:
  - base-apache
  - nagios
  
  tags:
  - monitoring
