---
- name: Basic facts gathering example
  hosts: all
  gather_facts: no
  vars:

  tasks:

  - name: collect default set of facts and configuration
    junos_facts:
      gather_subset: config
    register: junosfacts
