---
- name: Basic facts gathering example
  hosts: all
  gather_facts: no
  vars:

  tasks:

  - name: collect junos version information 
    junos_command:
      commands: show version
    register: junos_version

  - name: collect default set of facts and configuration
    junos_facts:
