---
- name: Basic facts gathering example
  hosts: all
  gather_facts: no
  vars:

  tasks:

  - name: collect default set of facts and configuration
    junos_command:
      commands: show version
    #junos_facts:
    register: junos_version
