---
- include: setup-RedHat.yml
  when: ansible_os_family == 'RedHat'

- include: setup-Debian.yml
  when: ansible_os_family == 'Debian'

- name: Install Kibana.
  package: name=kibana state=present

- name: Ensure Kibana is started and enabled at boot.
  service:
    name: kibana
#    state: started
    enabled: yes

- name: add kibana config directory
  file: path=/usr/share/kibana/config
    state=directory
    owner=kibana
    group=kibana
    mode=0755

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/usr/share/kibana/config/kibana.yml"
    owner: root
    group: root
    mode: 0644
#  notify: restart kibana
