# Description
# ===========
# This playbook prints our hidden variables....
# Must always observe what is being checked into your repo..
# Implement good coding practices

---
- name : Show my credentials
  hosts: localhost 
  gather_facts: False
  vars:

  tasks:

    - block:
      - debug: msg={{ ec2_access_key }}
      - debug: msg={{ ec2_secret_key }}
      #- debug: msg={{ lookup('env', 'AWS_ACCESS_KEY_ID') }}
      #- debug: msg={{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}
