# Description
# ===========
# This playbook create an Azure VM with public IP, and open 22 port for SSH
# This playbook creates an EC2 VM with public IP, and assign to security group with port 22 open.

---
- name : Simple playbook
  hosts: localhost 
  vars:
    cloud_provider: ''
    azurewebservers:
      - { vmname: 'webserver1', nic: 'webserver1' }
      - { vmname: 'webserver2', nic: 'webserver2' }

    dynamic_inventory_tag: []

  tasks:

    - block:
      - name: EC2 Launch webserver instances
        ec2:
          image: "{{ ec2_image }}"
          instance_type: "{{ ec2_instance_type }}"
          aws_access_key: "{{ ec2_access_key }}"
          aws_secret_key: "{{ ec2_secret_key }}"
          key_name: "{{ ec2_keypair }}"
          region: "{{ ec2_region }}"
          wait: true
          count: "{{ ec2_webserver_instance_count }}"
          instance_tags: "{'ansible_group':'webservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
          vpc_subnet_id: "{{ ec2_subnet_id }}"
          assign_public_ip: yes
          group_id: "{{ ec2_security_group }}"
        register: ec2

      - name: EC2 Launch database instance
        ec2:
          image: "{{ ec2_image }}"
          instance_type: "{{ ec2_instance_type }}"
          aws_access_key: "{{ ec2_access_key }}"
          aws_secret_key: "{{ ec2_secret_key }}"
          key_name: "{{ ec2_keypair }}"
          region: "{{ ec2_region }}"
          wait: true
          count: "{{ ec2_dbserver_instance_count|int }}"
          instance_tags: "{'ansible_group':'dbservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
          vpc_subnet_id: "{{ ec2_subnet_id }}"
          assign_public_ip: yes
          group_id: "{{ ec2_security_group }}"  # or you can say 'default' here
        register: ec2

      - name: EC2 Launch load balancing instance
        ec2:
          image: "{{ ec2_image }}"
          instance_type: "{{ ec2_instance_type }}"
          aws_access_key: "{{ ec2_access_key }}"
          aws_secret_key: "{{ ec2_secret_key }}"
          key_name: "{{ ec2_keypair }}"
          region: "{{ ec2_region }}"
          wait: true
          count: "{{ ec2_lbserver_instance_count|int }}"
          instance_tags: "{'ansible_group':'lbservers', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
          vpc_subnet_id: "{{ ec2_subnet_id }}"
          assign_public_ip: yes
          group_id: "{{ ec2_security_group }}"  # or you can say 'default' here
        register: ec2

      - name: EC2 Launch monitoring instance
        ec2:
          image: "{{ ec2_image }}"
          instance_type: "{{ ec2_instance_type }}"
          aws_access_key: "{{ ec2_access_key }}"
          aws_secret_key: "{{ ec2_secret_key }}"
          key_name: "{{ ec2_keypair }}"
          region: "{{ ec2_region }}" 
          wait: true
          count: "{{ ec2_monitoring_instance_count|int }}"
          instance_tags: "{'ansible_group':'monitoring', 'type':'{{ ec2_instance_type }}', 'group':'{{ ec2_security_group }}', 'Name':'demo_''{{ tower_user_name }}'}"
          vpc_subnet_id: "{{ ec2_subnet_id }}"
          assign_public_ip: yes
          group_id: "{{ ec2_security_group }}"  # or you can say 'default' here
        register: ec2

      - name: EC2 Wait for SSH to come up
        wait_for:
          host: "{{ item.public_dns_name }}"
          port: 22
          delay: 60
          timeout: 320
          state: started
        with_items: "{{ ec2.instances }}"

      when: cloud_provider == 'ec2'

    - block:
      - name: Azure Create virtual network
        azure_rm_virtualnetwork:
          resource_group: "{{ resource_group }}"
          name: "{{ vm_name }}"
          address_prefixes: "10.0.0.0/16"
      - name: Azure Add subnet
        azure_rm_subnet:
          resource_group: "{{ resource_group }}"
          name: "{{ vm_name }}"
          address_prefix: "10.0.1.0/24"
          virtual_network: "{{ vm_name }}"
      - name: Azure Create Network Security Group that allows SSH
        azure_rm_securitygroup:
          resource_group: "{{ resource_group }}"
          name: "{{ vm_name }}"
          rules:
            - name: SSH
              protocol: Tcp
              destination_port_range: 22
              access: Allow
              priority: 1001
              direction: Inbound
            - name: HTTP
              protocol: Tcp
              destination_port_range: 80
              access: Allow
              priority: 1002
              direction: Inbound
            - name: HTTPS
              protocol: Tcp
              destination_port_range: 443
              access: Allow
              priority: 1003
              direction: Inbound
            - name: LB
              protocol: Tcp
              destination_port_range: 8888
              access: Allow
              priority: 1004
              direction: Inbound

      # Create Webserver
      - name: Azure Create Webserver public IP address
        azure_rm_publicipaddress:
          resource_group: "{{ resource_group }}"
          allocation_method: Static
          name: "{{ item.vmname }}IP"
        with_items : "{{ azurewebservers }}"
      - name: Azure Create Webserver virtual network inteface card
        azure_rm_networkinterface:
          resource_group: "{{ resource_group }}"
          name: "{{ item.vmname }}NIC"
          virtual_network: "{{ vm_name }}"
          subnet: "{{ vm_name }}"
          public_ip_name: "{{ item.vmname }}IP"
          security_group: "{{ vm_name }}"
        with_items : "{{ azurewebservers }}"
      - name: Azure Create Webserver VM
        azure_rm_virtualmachine:
          resource_group: "{{ resource_group }}"
          name: "{{ item.vmname }}VM"
          vm_size: Standard_DS1_v2
          admin_username: ec2-user
          admin_password: Password@123
          tags:
            tag_ansible_group : webservers
          ssh_public_keys:
            - path: /home/ec2-user/.ssh/authorized_keys
              key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClKymYHNpAnt+WNwkQglhYNRb8dnFOyxduXORciKkb7fGE1li1MokcL9lgGmRPacueI3ssSvjvZzXBT0p2H2jrNfRKvI7vLTBIPq/cfVzBbYgSselELb0IMob5AKht/FS6k++Obmz5GZj+HLzBwDTTEwTJfWu+joc2dTdOWtiFQjzQJLjzyFGR/Kt5WtucS62rfPGp1jqqZ75EmxfiRJaGziTgdO8Nns/9fMpUanqYF0LOWhuK+RJK3YDPo40PIpiykNgqss+s/tID4qwfonl7/JJWoHyYTRGK+c7xV2FukGIH4eLy3+ufEI4JVMR7GLEQljVo1AvwF66mnyoemuur etg-richard 
          network_interfaces: "{{ item.vmname }}NIC"
          image:
            offer: RHEL
            publisher: RedHat
            sku: 7.3
            version: latest
        with_items: "{{ azurewebservers }}"

      # Create dbserver
      - name: Azure Create dbserver public IP address
        azure_rm_publicipaddress:
          resource_group: "{{ resource_group }}"
          allocation_method: Static
          name: dbserver
      - name: Azure Create dbserver virtual network inteface card
        azure_rm_networkinterface:
          resource_group: "{{ resource_group }}"
          name: dbserver
          virtual_network: "{{ vm_name }}"
          subnet: "{{ vm_name }}"
          public_ip_name: dbserver
          security_group: "{{ vm_name }}"
      - name: Azure Create dbserver VM
        azure_rm_virtualmachine:
          resource_group: "{{ resource_group }}"
          name: dbserver
          vm_size: Standard_DS1_v2
          admin_username: ec2-user 
          admin_password: Password@123
          tags:
            tag_ansible_group : dbservers
          ssh_public_keys:
            - path: /home/ec2-user/.ssh/authorized_keys
              key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClKymYHNpAnt+WNwkQglhYNRb8dnFOyxduXORciKkb7fGE1li1MokcL9lgGmRPacueI3ssSvjvZzXBT0p2H2jrNfRKvI7vLTBIPq/cfVzBbYgSselELb0IMob5AKht/FS6k++Obmz5GZj+HLzBwDTTEwTJfWu+joc2dTdOWtiFQjzQJLjzyFGR/Kt5WtucS62rfPGp1jqqZ75EmxfiRJaGziTgdO8Nns/9fMpUanqYF0LOWhuK+RJK3YDPo40PIpiykNgqss+s/tID4qwfonl7/JJWoHyYTRGK+c7xV2FukGIH4eLy3+ufEI4JVMR7GLEQljVo1AvwF66mnyoemuur etg-richard 
          network_interfaces: dbserver
          image:
            offer: RHEL
            publisher: RedHat 
            sku: 7.3 
            version: latest

      # Create load balancer
      - name: Create load balancer public IP address
        azure_rm_publicipaddress:
          resource_group: "{{ resource_group }}"
          allocation_method: Static
          name: lbservers
      - name: Create load balancer virtual network inteface card
        azure_rm_networkinterface:
          resource_group: "{{ resource_group }}"
          name: lbservers
          virtual_network: "{{ vm_name }}"
          subnet: "{{ vm_name }}"
          public_ip_name: lbservers
          security_group: "{{ vm_name }}"
      - name: Azure Create load balancer VM
        azure_rm_virtualmachine:
          resource_group: "{{ resource_group }}"
          name: lbservers
          vm_size: Standard_DS1_v2
          admin_username: ec2-user 
          admin_password: Password@123
          tags:
            tag_ansible_group : lbservers
          ssh_public_keys:
            - path: /home/ec2-user/.ssh/authorized_keys
              key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClKymYHNpAnt+WNwkQglhYNRb8dnFOyxduXORciKkb7fGE1li1MokcL9lgGmRPacueI3ssSvjvZzXBT0p2H2jrNfRKvI7vLTBIPq/cfVzBbYgSselELb0IMob5AKht/FS6k++Obmz5GZj+HLzBwDTTEwTJfWu+joc2dTdOWtiFQjzQJLjzyFGR/Kt5WtucS62rfPGp1jqqZ75EmxfiRJaGziTgdO8Nns/9fMpUanqYF0LOWhuK+RJK3YDPo40PIpiykNgqss+s/tID4qwfonl7/JJWoHyYTRGK+c7xV2FukGIH4eLy3+ufEI4JVMR7GLEQljVo1AvwF66mnyoemuur etg-richard 
          network_interfaces: lbservers
          image:
            offer: RHEL
            publisher: RedHat 
            sku: 7.3 
            version: latest

      # Create monitoring
      - name: Create monitoring public IP address
        azure_rm_publicipaddress:
          resource_group: "{{ resource_group }}"
          allocation_method: Static
          name: monitoring
      - name: Create monitoring virtual network inteface card
        azure_rm_networkinterface:
          resource_group: "{{ resource_group }}"
          name: monitoring
          virtual_network: "{{ vm_name }}"
          subnet: "{{ vm_name }}"
          public_ip_name: monitoring
          security_group: "{{ vm_name }}"
      - name: Aure Create monitoring VM
        azure_rm_virtualmachine:
          resource_group: "{{ resource_group }}"
          name: monitoring
          vm_size: Standard_DS1_v2
          admin_username: ec2-user 
          admin_password: Password@123
          tags:
            tag_ansible_group : monitoring
          ssh_public_keys:
            - path: /home/ec2-user/.ssh/authorized_keys
              key_data: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQClKymYHNpAnt+WNwkQglhYNRb8dnFOyxduXORciKkb7fGE1li1MokcL9lgGmRPacueI3ssSvjvZzXBT0p2H2jrNfRKvI7vLTBIPq/cfVzBbYgSselELb0IMob5AKht/FS6k++Obmz5GZj+HLzBwDTTEwTJfWu+joc2dTdOWtiFQjzQJLjzyFGR/Kt5WtucS62rfPGp1jqqZ75EmxfiRJaGziTgdO8Nns/9fMpUanqYF0LOWhuK+RJK3YDPo40PIpiykNgqss+s/tID4qwfonl7/JJWoHyYTRGK+c7xV2FukGIH4eLy3+ufEI4JVMR7GLEQljVo1AvwF66mnyoemuur etg-richard 
          network_interfaces: monitoring
          image:
            offer: RHEL
            publisher: RedHat 
            sku: 7.3 
            version: latest
        register: output

#      - debug: var=output

#
#  - name: Populate dictionary for inventory import 
#    set_fact:
#      dynamic_inventory_tag: "{{ dynamic_inventory_tag|default([]) + [ {'instance_id': item.id, 'ip': item.public_ip} ] }}"
#      #dynamic_inventory_tag: "{{ dynamic_inventory_tag|default([]) + [ {'instance_id': item.instance_id, 'ip': item.public_ip_address} ] }}"
#    with_items: "{{ ec2.instances }}"
# add_host and then delegate_to for triggering the next peiece in the workflow....maybe a handler

      when: cloud_provider == 'azure'
