- name: Add a new account to Active Directory
  hosts: all
  tasks:


   - name: ensure the group exists
     win_domain_group:
      name: "{{ group_name }}" 
      scope: global
      path: CN=Users,DC=redhat,DC=local


   - name: Ensure user is present
     win_domain_user:
       name: "{{ user_name }}" 
       firstname: "{{ first_name }}" 
       surname: "{{ last_name }}" 
       company: "{{ company_name }}" 
       password: "{{ user_password }}" 
       state: present
       description: "{{ first_name }} {{ last_name }}"
       groups:
         - Domain Users
         - Ansible Admins
       street: 123 4th St.
       city: Sometown
       state_province: IN
       postal_code: 12345
       country: US
       attributes:
         telephoneNumber: 555-123456
       path: cn=Users,dc=redhat,dc=local
